"""empty message

Revision ID: 2175023d9e74
Revises: ecee03a4d18
Create Date: 2014-10-29 10:03:34.240908

"""

# revision identifiers, used by Alembic.
revision = '2175023d9e74'
down_revision = 'ecee03a4d18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('openid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
